### ISSUE TITLE
nodetool listsnapshots fails when rerunning during a restarted backup task

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#2886]
manager version: 2.5.2-0.20210915.8f0ca31a
The scenario goes as follows:

First, we start a normal backup, wait for it to start to run and then restart the manager server and see that the task was aborted.
Afterwards, we examine the existing snapshots in the cluster, by running nodetool listsnapshots (which works perfectly fine at this point).

Afterwards, we restart all of the agents and start the backup task again (without continuing it), wait for it to start running and executing listsnapshots again. Only that this time, the command fails:
```
java.lang.IllegalStateException: Scylla API server HTTP GET to URL '/storage_service/snapshots/size/true' failed: std::runtime_error (Failed to get /jenkins/slave/workspace/manager-2.5/manager-dtest/scylla-dtest/tmp_dtest_run/.dtest/dtest-i_lmo2f2/test/node1/data/keyspace1/standard1-1577b7f01f6811ecb6e53f188daff7e8/snapshots/sm_20210927075710UTC/md-67-big-Statistics.db type.)
	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:140)
	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:187)
	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:209)
	at com.scylladb.jmx.api.APIClient.getLongValue(APIClient.java:512)
	at org.apache.cassandra.service.StorageService.trueSnapshotsSize(StorageService.java:644)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:188)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
What changed with the second command execution?

**Comment by mmatczuk** [comment]
As we delete files as we go Scylla API fails with error code in listing.
This is a regression added in 2.5.

**Comment by mmatczuk** [comment]
I think there may be a race condition between agent removing files and you checking.
I'd recommend wrapping the call in a retry.

Removing files and then calling listsnapshots does not crash and the accounting is done correctly.

```
[root@62d8ae1fe669 xxx]# nodetool listsnapshots 
Snapshot Details: 
Snapshot name Keyspace name            Column family name True size Size on disk
xxx           backuptest_foo1636117669 c                  0 bytes   1.2 MB      
xxx           backuptest_foo1636117669 a                  0 bytes   1.2 MB      
xxx           backuptest_foo1636117669 b                  0 bytes   1.2 MB      
[root@62d8ae1fe669 xxx]# rm -f md-2-big-Filter.db
[root@62d8ae1fe669 xxx]# nodetool listsnapshots 
Snapshot Details: 
Snapshot name Keyspace name            Column family name True size Size on disk
xxx           backuptest_foo1636117669 c                  0 bytes   1.2 MB      
xxx           backuptest_foo1636117669 b                  0 bytes   1.2 MB      
xxx           backuptest_foo1636117669 a                  0 bytes   613.17 KB   
```

**Comment by rayakurl** [comment]
@tzach -FYI. This issue might happen in 2.6.

**Comment by karol-kokoszka** [comment]
@ShlomiBalalis are you working on this task ?
Is is something that was found with the dtests ?

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis are you working on this task ? Is is something that was found with the dtests ?

It was in the dtests, yes. But I don't recall seeing it reproduced since 2.6, so I think it's safe to close this one
