### ISSUE TITLE
client: http request from generated client is not timing out

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#2949]
Http request made with provided scylla-manager client doesn't timeout when request hangs.
As a manager API consumers we can only override http transport, but transport defines timeouts for dialing, `keep-alive` etc.
To override the request timeout, there is a need to update the client:
https://github.com/scylladb/scylla-manager/blob/9c54d1ac5aa26e4427660307e3d85621ec8a8869/pkg/managerclient/client.go#L74-L76

with 
```
	httpClient := &http.Client{
		Transport: transport,
		Timeout: 30 * time.Second,
	}
```

See the memory dump of timed out test:
```
goroutine 11111 [select]:
net/http.(*Transport).getConn(0xc000c2c780, 0xc000e9e0c0, 0x0, 0xc000c27980, 0x5, 0xc000fc2018, 0x13, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1368 +0x9ba
net/http.(*Transport).roundTrip(0xc000c2c780, 0xc0012b8400, 0xc000fce1f8, 0xc0008602d0, 0x4d)
	/usr/local/go/src/net/http/transport.go:579 +0xafb
net/http.(*Transport).RoundTrip(0xc000c2c780, 0xc0012b8400, 0xc000c2c780, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x47
net/http.send(0xc0012b8400, 0x47d2d20, 0xc000c2c780, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000aca060, 0xc000ec09b8)
	/usr/local/go/src/net/http/client.go:251 +0x6db
net/http.(*Client).send(0xc000a6eea0, 0xc0012b8400, 0x0, 0x0, 0x0, 0xc000aca060, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:175 +0x1d6
net/http.(*Client).do(0xc000a6eea0, 0xc0012b8400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:717 +0x2cc
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:585
github.com/go-openapi/runtime/client.(*Runtime).Submit(0xc001021520, 0xc000286240, 0x0, 0x0, 0x0, 0x0)
	/XXXXXXXXXXXXXr/github.com/go-openapi/runtime/client/runtime.go:435 +0xc07
github.com/scylladb/scylla-manager/swagger/gen/scylla-manager/client/operations.(*Client).GetClusterClusterIDTaskTaskTypeTaskIDHistory(0xc00026d240, 0xc000b8a360, 0xc000ede030, 0x24, 0xc000d60210)
	/XXXXXXXXXXXX/github.com/scylladb/scylla-manager/swagger/gen/scylla-manager/client/operations/operations_client.go:457 +0x591
github.com/scylladb/scylla-manager/pkg/managerclient.(*Client).GetTaskHistory(0xc001447ea0, 0x48087c0, 0xc000c238f0, 0xc000e300a8, 0x2, 0x3c4531f, 0x6, 0x2c4bbe8dad0c45a1, 0xe929a3d8f308c2b4, 0x1, ...)
	/XXXXXXXXXXXXXXXX/managerclient/client.go:240 +0x268
```

One of the recent timeout definition on default transport touched dialing only and solves hanging on tcp dial.
https://github.com/scylladb/scylla-manager/commit/44c8d4f2008660e11ad1a8adc6381c7231b68c10

**Comment by mmatczuk** [comment]
I'd add options to allow decorating the client.
