### ISSUE TITLE
Suspend command fails: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3076]
Version: 3.0-dev-0.20220316.7ffa705f546

At first I start a backup and wait for it to reach `RUNNING` status:
`sctool backup -c 026f8c00-99f9-4aa6-ab8b-c905e10c359e --location s3:manager-backup-tests-us-east-1`
```
< t:2022-03-16 21:31:12,751 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo sctool  -c 026f8c00-99f9-4aa6-ab8b-c905e10c359e progress backup/2e11127f-fa66-4804-9ce7-0bf0285b46d1"...
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Run:            655c7acf-a570-11ec-a02a-022d1d436c67
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status:         RUNNING (taking snapshot)
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Start time:     16 Mar 22 21:31:09 UTC
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Duration:       3s
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Progress:       -
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Snapshot Tag:   sm_20220316213111UTC
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Datacenters:    
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   - us-eastscylla_node_east
< t:2022-03-16 21:31:12,866 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   - us-west-2scylla_node_west
```
Afterwards, I suspend the cluster:
```
< t:2022-03-16 21:31:14,571 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo sctool suspend -c 026f8c00-99f9-4aa6-ab8b-c905e10c359e"...
< t:2022-03-16 21:31:15,614 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2022-03-16 21:31:15,614 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo sctool suspend -c 026f8c00-99f9-4aa6-ab8b-c905e10c359e"; Exit status: 1
< t:2022-03-16 21:31:15,614 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: Error: Put "http://127.0.0.1:5080/api/v1/cluster/026f8c00-99f9-4aa6-ab8b-c905e10c359e/suspended?start_tasks=false": EOF
```
From the server's log:
```
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 scylla-manager[10886]: {"L":"INFO","T":"2022-03-16T21:31:14.068Z","N":"http","M":"GET /api/v1/cluster/026f8c00-99f9-4aa6-ab8b-c905e10c359e/tasks?all=false","from":"127.0.0.1:42124","status":200,"bytes":1934,"durati
on":"3ms","_trace_id":"myRxD48CTMmoKiJwGUDrRg"}
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 scylla-manager[10886]: {"L":"INFO","T":"2022-03-16T21:31:14.678Z","N":"scheduler","M":"Suspending cluster","cluster_id":"026f8c00-99f9-4aa6-ab8b-c905e10c359e","_trace_id":"8l10UknnRbiILFdObq4ZfA"}
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 scylla-manager[10886]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 systemd[1]: scylla-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 systemd[1]: Unit scylla-manager.service entered failed state.
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 systemd[1]: scylla-manager.service failed.
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 systemd[1]: scylla-manager.service holdoff time over, scheduling restart.
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 systemd[1]: Stopped Scylla Manager Server.
Mar 16 21:31:14 manager-regression-manager--monitor-node-65ae8186-1 systemd[1]: Started Scylla Manager Server.
Mar 16 21:31:15 manager-regression-manager--monitor-node-65ae8186-1 scylla-manager[11408]: {"L":"INFO","T":"2022-03-16T21:31:15.049Z","M":"Scylla Manager Server","version":"3.0-dev-0.20220316.7ffa705f546","pid":11408,"_trace_id":"s_qzqw8PQGW0J2Ss-e2zJg"}
```

Same error type as in https://github.com/scylladb/scylla-manager/issues/3064 

Logs:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                             Log links for testrun with test id 65ae8186-845e-48c9-9fd2-fef5ff9b6894                                             |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                            |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
| 20220316_215925 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/65ae8186-845e-48c9-9fd2-fef5ff9b6894/20220316_215925/db-cluster-65ae8186.tar.gz  |
| 20220316_215925 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/65ae8186-845e-48c9-9fd2-fef5ff9b6894/20220316_215925/loader-set-65ae8186.tar.gz  |
| 20220316_215925 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/65ae8186-845e-48c9-9fd2-fef5ff9b6894/20220316_215925/monitor-set-65ae8186.tar.gz |
| 20220316_215925 | sct         | https://cloudius-jenkins-test.s3.amazonaws.com/65ae8186-845e-48c9-9fd2-fef5ff9b6894/20220316_215925/sct-runner-65ae8186.tar.gz  |
+-----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------+
```
(manager server log is under monitor-set, agent logs is under db-cluster)

**Comment by ShlomiBalalis** [comment]
The traceback:
```
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12a2aa6]
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: goroutine 534 [running]:
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: github.com/scylladb/scylla-manager/pkg/scyllaclient.(*Client).RcloneListDirIter(0xc00057a420, 0x2d717d0, 0xc0007eb590, 0xc0006c7f80, 0xc, 0xc0009b13e0, 0x60, 0xc000759774, 0xc0007599d0, 0x0, ...)
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]:         github.com/scylladb/scylla-manager/pkg/scyllaclient/client_rclone.go:449 +0x586
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: github.com/scylladb/scylla-manager/pkg/service/backup.(*worker).indexSnapshotDirs(0xc00001eb40, 0x2d717d0, 0xc0007eb590, 0xc000346bc0, 0x19, 0xc0006c7f80, 0xc, 0xc00083a750, 0x24, 0x0, ...)
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]:         github.com/scylladb/scylla-manager/pkg/service/backup/worker_index.go:117 +0x912
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: github.com/scylladb/scylla-manager/pkg/service/backup.(*worker).Index.func2(0xc000346bc0, 0x19, 0xc0006c7f80, 0xc, 0xc00083a750, 0x24, 0x0, 0x0, 0xc000c854b8, 0x2, ...)
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]:         github.com/scylladb/scylla-manager/pkg/service/backup/worker_index.go:33 +0x1a5
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: github.com/scylladb/scylla-manager/pkg/service/backup.hostsInParallel.func1(0x2, 0xc0007bd040, 0xc0007f94a0)
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]:         github.com/scylladb/scylla-manager/pkg/service/backup/parallel.go:80 +0xd9
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: github.com/scylladb/scylla-manager/pkg/util/parallel.Run.func1(0xc000564970, 0x3, 0xc000564978, 0xc0007f6f00, 0xc000a11b60)
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]:         github.com/scylladb/scylla-manager/pkg/util/parallel/parallel.go:69 +0x7f
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]: created by github.com/scylladb/scylla-manager/pkg/util/parallel.Run
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 scylla-manager[31014]:         github.com/scylladb/scylla-manager/pkg/util/parallel/parallel.go:54 +0x132
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 systemd[1]: scylla-manager.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 22 22:07:27 manager-regression-manager--monitor-node-40d961bc-1 systemd[1]: scylla-manager.service: Failed with result 'exit-code'.
Mar 22 22:07:28 manager-regression-manager--monitor-node-40d961bc-1 systemd[1]: scylla-manager.service: Service hold-off time over, scheduling restart.
Mar 22 22:07:28 manager-regression-manager--monitor-node-40d961bc-1 systemd[1]: scylla-manager.service: Scheduled restart job, restart counter is at 1.
```
