### ISSUE TITLE
GCE restore fails near instantly, even though it is marked as DONE

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-manager#3382]
Client version: 3.1.0-0.20230428.eef5b774
Server version: 3.1.0-0.20230428.eef5b774

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

This issue is gcp specific, and does not reproduce with s3/azure.
At first, we ran a simple, keyspace specific backup, which ran until completion:
```
< t:2023-05-02 11:41:35,585 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "sudo sctool backup -c 93ae0a17-eae5-4eaa-9486-e6587926cec3 --keyspace keyspace1  --location gcs:manager-backup-tests-sct-project-1-us-east1 " finished with status 0
< t:2023-05-02 11:41:35,585 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > sctool output: backup/8be4c092-8dcd-4766-9b43-ec7153e0e6ac
...
< t:2023-05-02 11:42:44,117 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "sudo sctool  -c 93ae0a17-eae5-4eaa-9486-e6587926cec3 progress backup/8be4c092-8dcd-4766-9b43-ec7153e0e6ac" finished with status 0
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > sctool output: Run:               4aa17e83-e8de-11ed-8804-42010a8e0032
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Status:           DONE
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Start time:       02 May 23 11:41:35 UTC
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > End time: 02 May 23 11:41:53 UTC
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Duration: 18s
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Progress: 100%
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Snapshot Tag:     sm_20230502114137UTC
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Datacenters:      
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG >   - us-east1scylla_node_east
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG >   - us-west1scylla_node_west
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > 
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > ╭──────────────┬──────────┬──────────┬──────────┬──────────────┬────────╮
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > │ Host         │ Progress │     Size │  Success │ Deduplicated │ Failed │
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > ├──────────────┼──────────┼──────────┼──────────┼──────────────┼────────┤
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > │ 10.138.0.50  │     100% │ 353.856k │ 353.856k │     353.856k │      0 │
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > │ 10.142.0.247 │     100% │ 351.474k │ 351.474k │     351.474k │      0 │
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > │ 10.142.0.40  │     100% │ 353.585k │ 353.585k │     353.585k │      0 │
< t:2023-05-02 11:42:44,119 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > ╰──────────────┴──────────┴──────────┴──────────┴──────────────┴────────╯
```
Afterwards, we truncate the keyspace
```
< t:2023-05-02 11:42:47,574 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "TRUNCATE keyspace1.standard1" 10.142.0.247 9042" finished with status 0
```
and restore the backup:
```
< t:2023-05-02 11:42:52,965 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "sudo sctool restore -c 93ae0a17-eae5-4eaa-9486-e6587926cec3 --restore-tables --location gcs:manager-backup-tests-sct-project-1-us-east1  --snapshot-tag sm_20230502114137UTC" finished with status 0
< t:2023-05-02 11:42:52,965 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > sctool output: restore/9d251f68-4ac3-4caf-9c22-0b858d0dc6f8
...
< t:2023-05-02 11:43:31,473 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "sudo sctool  -c 93ae0a17-eae5-4eaa-9486-e6587926cec3 progress restore/9d251f68-4ac3-4caf-9c22-0b858d0dc6f8" finished with status 0
< t:2023-05-02 11:43:31,473 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > sctool output: Run:               78c09e3d-e8de-11ed-8805-42010a8e0032
< t:2023-05-02 11:43:31,473 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Status:           DONE - tombstone_gc mode reset and repair required (see restore docs)
< t:2023-05-02 11:43:31,473 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Start time:       02 May 23 11:42:52 UTC
< t:2023-05-02 11:43:31,473 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > End time: 02 May 23 11:42:58 UTC
< t:2023-05-02 11:43:31,473 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Duration: 5s
< t:2023-05-02 11:43:31,473 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Progress: -
< t:2023-05-02 11:43:31,473 f:cli.py          l:1110 c:sdcm.mgmt.cli        p:DEBUG > Snapshot Tag:     sm_20230502114137UTC
```
First and foremost, it's already strange that the restore has ended in 5 seconds (with other backends, it took 1.5 to 2.5 minutes), with the progress stated as `-` as opposed to a percentage, and the keyspace/progress table completely missing.
Still, afterwards, we executed a repair and ran a C-S thread to verify data integrity. The C-S thread failed immidiately, stating that the data could not be validated:
```
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
Failed to connect over JMX; not collecting these stats
java.io.IOException: Operation x0 on key(s) [305034304c4c34373330]: Data returned was not validated

        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
java.io.IOException: Operation x0 on key(s) [3138344e4d4d4e503430]: Data returned was not validated
```

## Impact

If consistent, could spell a severe issue with gce restoration.

## How frequently does it reproduce?

So far, only one run of said scenario has ran, so it's unclear.

## Installation details

Kernel Version: 5.15.0-1032-gcp
Scylla version (or git commit hash): `5.1.9-20230423.ba1a57bd5531` with build-id `dc1d4a867f95e936e52c60fa6f3cfe15654f0de4`

Cluster size: 3 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- manager-regression-restore--db-node-5bfd7570-1-3 (34.83.242.98 | 10.138.0.50) (shards: 7)
- manager-regression-restore--db-node-5bfd7570-0-2 (35.231.211.56 | 10.142.0.40) (shards: 7)
- manager-regression-restore--db-node-5bfd7570-0-1 (35.196.154.207 | 10.142.0.247) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-5-1-9-x86-64-2023-04-23t12-04-04z` (gce: us-east1)

Test: `sct-feature-test-backup-gce`
Test id: `5bfd7570-c0e8-4f3d-969f-c06250340062`
Test name: `scylla-staging/Shlomo/sct-feature-test-backup-gce`
Test config file(s):

- [manager-regression-multiDC-gce.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/27c3f6e1f1f76517ebb572774dda472ccd0fb3e5/test-cases/manager/manager-regression-multiDC-gce.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5bfd7570-c0e8-4f3d-969f-c06250340062`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5bfd7570-c0e8-4f3d-969f-c06250340062)
- Show all stored logs command: `$ hydra investigate show-logs 5bfd7570-c0e8-4f3d-969f-c06250340062`

## Logs:
+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                Collected logs by test-id: 5bfd7570-c0e8-4f3d-969f-c06250340062                                                |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| Cluster set           | Link                                                                                                                                  |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| db-cluster            | https://cloudius-jenkins-test.s3.amazonaws.com/5bfd7570-c0e8-4f3d-969f-c06250340062/20230502_142906/db-cluster-5bfd7570.tar.gz        |
| sct-runner-events     | https://cloudius-jenkins-test.s3.amazonaws.com/5bfd7570-c0e8-4f3d-969f-c06250340062/20230502_142906/sct-runner-events-5bfd7570.tar.gz |
| sct-runner-python-log | https://cloudius-jenkins-test.s3.amazonaws.com/5bfd7570-c0e8-4f3d-969f-c06250340062/20230502_142906/sct-5bfd7570.log.tar.gz           |
| loader-set            | https://cloudius-jenkins-test.s3.amazonaws.com/5bfd7570-c0e8-4f3d-969f-c06250340062/20230502_142906/loader-set-5bfd7570.tar.gz        |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------+
[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/Shlomo/job/sct-feature-test-backup-gce/1/)
</details>

**Edit**: Since log collection is a bit problematic ATM, here is the manager log: gs://scratch.scylladb.com/balalis/3382/scylla_manager.log

**Comment by ShlomiBalalis** [comment]
> nit: please re-run it with 5.1.8, not 5.1.9-20230423.ba1a57bd5531, just to make sure it's not a 5.1.9 regression.

Will do

**Comment by mykaul** [comment]
Either unrelated, or part of the test should be changed, or something else, but:
```
2023-05-02T14:28:35+00:00 manager-regression-restore--db-node-5bfd7570-0-1  !WARNING | scylla[8089]:  [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
2023-05-02T14:28:35+00:00 manager-regression-restore--db-node-5bfd7570-0-1  !WARNING | scylla[8089]:  [shard 0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
```
isn't something we should be seeing here?

**Comment by mykaul** [comment]
Oh, that can explain much of the issue:
```
2023-05-02T14:29:04+00:00 manager-regression-restore--db-node-5bfd7570-0-2  !WARNING | scylla[17855]:  [shard 0] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 28: filesystem error: mkdir failed: No space left on device [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/11557.sstable]). Will retry in 10000ms
```

**Comment by ShlomiBalalis** [comment]
> Oh, that can explain much of the issue:
> 
> ```
> 2023-05-02T14:29:04+00:00 manager-regression-restore--db-node-5bfd7570-0-2  !WARNING | scylla[17855]:  [shard 0] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 28: filesystem error: mkdir failed: No space left on device [/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/11557.sstable]). Will retry in 10000ms
> ```

This is from later down the line, at the end of the scenario (two hours later). There, we execute 2 End of space tests. Not related to this failure.

**Comment by mykaul** [comment]
During the **relevant** timeframe, I see (node 1):
reactor stall:
```
2023-05-02T11:43:38+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]: Reactor stalled for 151 ms on shard 0. Backtrace: 0x4d48902 0x4d47560 0x4d48810 0x7efce52a5a1f 0x7efce49e0236 0x2c4de67 0xf59a 0x117c4 0x36e53e6 0x50ed3b9 0x36e4ab0 0x36d0d3c 0x36fee16 0x36fc726 0x36fa2f7 0x36f9306 0x36f0596 0x36e2658 0x4fc7561
2023-05-02T11:43:38+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]: kernel callstack: 0xffffffffffffff80 0xffffffffb8f6b6a8 0xffffffffb8f6c605 0xffffffffb8f6e7bd 0xffffffffb8eaa8d1 0xffffffffb8eaa9bd 0xffffffffb8eb7ed5 0xffffffffb8eb7f7d 0xffffffffb8eb80c7 0xffffffffb8eb8366 0xffffffffb8eabcd9 0xffffffffb8ef1aad 0xffffffffb8ef3289 0xffffffffb8ef683c 0xffffffffb8ef6b28 0xffffffffb8c9ed32 0xffffffffb99a0a77 0xffffffffb9a00b67
```

Repair succeeded, I think, on shard 0 - with another keyspace (perhaps belong to a different test?):
```
2023-05-02T11:43:42+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[0acd63a9-d24c-4539-9b04-101fddcdd8f3]: shard 0 stats: repair_reason=repair, keyspace=ks004, tables={table0076, table0088, table0091, table0010, table0055, table007, table0038, table0048, table0013, table0071, table0023, table0014, table0052, table0063, table0092, table0045, table0016, table0015, table0072, table0056, table0065, table0074, table0030, table0035, table0069, table0081, table0022, table002, table0058, table0096, table0089, table0093, table0018, table0090, table004, table0084, table008, table0027, table0064, table0094, table0054, table0044, table0043, table0083, table0011, table0021, table0017, table0082, table0060, table0036, table0029, table0046, table0019, table0068, table0050, table0085, table0040, table0097, table0034, table0057, table009, table0020, table0061, table0079, table0098, table0026, table0073, table003, table0012, table0047, table0025, table0086, table0066, table0077, table0099, table0078, table0033, table0042, table0059, table0095, table0037, table0062, table0032, table0053, table0031, table001, table0041, table0087, table0024, table0039, table005, table0028, table0080, table0051, table000, table006, table0049, table0075, table0070, table0067}, ranges_nr=256, round_nr=0, round_nr_fast_path_already_synced=0, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=0, tx_hashes_nr=0, rx_hashes_nr=0, duration=0 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={}, row_from_disk_nr={}, row_from_disk_bytes_per_sec={} MiB/s, row_from_disk_rows_per_sec={} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
2023-05-02T11:43:42+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[0acd63a9-d24c-4539-9b04-101fddcdd8f3]: shard 0 completed successfully, keyspace=ks004
```
(too bad the stats are all zero!)

reactor stall:
```
2023-05-02T11:43:42+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]: Reactor stalled for 297 ms on shard 6. Backtrace: 0x4d48902 0x4d47560 0x4d48810 0x7efce52a5a1f 0x1019fb 0xfa721 0xfaa69 0x50ed3f7 0x36e4ab0 0x36d0d3c 0x36fee16 0x36fc726 0x36fa2f7 0x36f9306 0x37032cb 0x4d580f4 0x4d594d7 0x4d78525 0x4d2be9a 0x92a4 0x100322
```

And:
```
2023-05-02T11:43:43+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]: Reactor stalled for 1064 ms on shard 3. Backtrace: 0x4d48902 0x4d47560 0x4d48810 0x7efce52a5a1f 0x7efce4823c00 0x4d1dcdb 0x7e577 0xfa4d5 0xfaa69 0x50ed3f7 0x36e4ab0 0x36d0d3c 0x36fee16 0x36fc726 0x36fa2f7 0x36f9306 0x37032cb 0x4d580f4 0x4d594d7 0x4d78525 0x4d2be9a 0x92a4 0x100322
```
And also:
```
2023-05-02T11:43:43+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]: Reactor stalled for 2348 ms on shard 6. Backtrace: 0x4d48902 0x4d47560 0x4d48810 0x7efce52a5a1f 0x7efce49e0240 0x2c4de67 0xf59a 0x117c4 0x36e53e6 0x50ed3b9 0x36e4ab0 0x36d0d3c 0x36fee16 0x36fc726 0x36fa2f7 0x36f9306 0x37032cb 0x4d580f4 0x4d594d7 0x4d78525 0x4d2be9a 0x92a4 0x100322
```

Here shard 2 completed:
```
2023-05-02T11:45:46+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 2] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 2 completed successfully, keyspace=keyspace1
```
And we start repair on shard 0 again, now with ks007 - unrelated?:
```
2023-05-02T11:45:46+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: completed successfully
2023-05-02T11:45:47+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[069d34e9-73c7-47d0-bcda-f9035b1611f7]: starting user-requested repair for keyspace ks007, repair id 4, options {{ trace -> false}, { jobThreads -> 1}, { incremental -> false}, { parallelism -> parallel}, { primaryRange -> false}}
2023-05-02T11:45:47+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[069d34e9-73c7-47d0-bcda-f9035b1611f7]: Skipped sending repair_flush_hints_batchlog to nodes=[10.142.0.247]
2023-05-02T11:45:47+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[069d34e9-73c7-47d0-bcda-f9035b1611f7]: Started to repair 1 out of 100 tables in keyspace=ks007, table=table0069, table_id=b7d68fc0-e8da-11ed-99ba-c5040fb7cf33, repair_reason=repair
```

And we do flood with too many logs for this process:
```
2023-05-02T11:45:47+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | systemd-journald[215]: Suppressed 141700 messages from scylla-server.service
```

And shard 0 did complete though:
```
2023-05-02T11:45:51+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[069d34e9-73c7-47d0-bcda-f9035b1611f7]: shard 0 stats: repair_reason=repair, keyspace=ks007, tables={table0069, table0035, table0081, table002, table0058, table0022, table0096, table003, table0093, table0018, table0090, table0074, table0030, table008, table0094, table0064, table0054, table0089, table0011, table0021, table0082, table0017, table0060, table0036, table0084, table0027, table004, table0019, table0050, table0068, table0085, table0040, table006, table000, table0057, table0034, table009, table0020, table0061, table0079, table0029, table0026, table0046, table0073, table0097, table0012, table0086, table0047, table0025, table0066, table0098, table0077, table0078, table0099, table0033, table0037, table0042, table0059, table0095, table001, table0041, table0087, table0039, table005, table0028, table0080, table0051, table0032, table0053, table0062, table0031, table0067, table0075, table0049, table0070, table0076, table0024, table0055, table007, table0038, table0048, table0083, table0023, table0044, table0043, table0071, table0014, table0052, table0063, table0092, table0088, table0091, table0010, table0016, table0045, table0015, table0013, table0072, table0056, table0065}, ranges_nr=256, round_nr=0, round_nr_fast_path_already_synced=0, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=0, tx_hashes_nr=0, rx_hashes_nr=0, duration=0 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={}, row_from_disk_nr={}, row_from_disk_bytes_per_sec={} MiB/s, row_from_disk_rows_per_sec={} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
2023-05-02T11:45:51+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[069d34e9-73c7-47d0-bcda-f9035b1611f7]: shard 0 completed successfully, keyspace=ks007
```

And shards 1-6 did complete as well later. So it's unclear wrt keyspace1, what failed. 
```
[ykaul@ykaul ~]$ grep -Frisn " completed successfully" /home/ykaul/Downloads/db-cluster-5bfd7570/manager-regression-restore--db-node-5bfd7570-0-1/messages.log |grep a8e1bef4be93 
52570:2023-05-02T11:44:59+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 4] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 4 completed successfully, keyspace=keyspace1
52573:2023-05-02T11:45:17+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 6] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 6 completed successfully, keyspace=keyspace1
52575:2023-05-02T11:45:19+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 1] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 1 completed successfully, keyspace=keyspace1
52579:2023-05-02T11:45:25+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 3] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 3 completed successfully, keyspace=keyspace1
52587:2023-05-02T11:45:38+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 5] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 5 completed successfully, keyspace=keyspace1
52589:2023-05-02T11:45:41+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 0 completed successfully, keyspace=keyspace1
52595:2023-05-02T11:45:46+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 2] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: shard 2 completed successfully, keyspace=keyspace1
52598:2023-05-02T11:45:46+00:00 manager-regression-restore--db-node-5bfd7570-0-1     !INFO | scylla[8089]:  [shard 0] repair - repair[69d435d8-4976-45c0-84d7-a8e1bef4be93]: completed successfully
```

(this is all on node1, did not yet looked at other nodes)

**Comment by mykaul** [comment]
Same on node2: 
```
135453:2023-05-02T12:11:32+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 2] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: shard 2 completed successfully, keyspace=keyspace1
135455:2023-05-02T12:11:32+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 3] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: shard 3 completed successfully, keyspace=keyspace1
135486:2023-05-02T12:11:48+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 5] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: shard 5 completed successfully, keyspace=keyspace1
135488:2023-05-02T12:11:53+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 0] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: shard 0 completed successfully, keyspace=keyspace1
135493:2023-05-02T12:12:03+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 6] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: shard 6 completed successfully, keyspace=keyspace1
135502:2023-05-02T12:12:19+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 4] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: shard 4 completed successfully, keyspace=keyspace1
135504:2023-05-02T12:12:20+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 1] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: shard 1 completed successfully, keyspace=keyspace1
135507:2023-05-02T12:12:20+00:00 manager-regression-restore--db-node-5bfd7570-0-2     !INFO | scylla[8316]:  [shard 0] repair - repair[4ff3e69c-d549-4eb7-a467-d20875e95ce9]: completed successfully
```

And node3:
```
57330:2023-05-02T12:14:28+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 1] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: shard 1 completed successfully, keyspace=keyspace1
57336:2023-05-02T12:14:38+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 3] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: shard 3 completed successfully, keyspace=keyspace1
57340:2023-05-02T12:14:49+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 5] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: shard 5 completed successfully, keyspace=keyspace1
57342:2023-05-02T12:14:52+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 4] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: shard 4 completed successfully, keyspace=keyspace1
57347:2023-05-02T12:15:06+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 2] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: shard 2 completed successfully, keyspace=keyspace1
57349:2023-05-02T12:15:07+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 0] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: shard 0 completed successfully, keyspace=keyspace1
57351:2023-05-02T12:15:13+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 6] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: shard 6 completed successfully, keyspace=keyspace1
57354:2023-05-02T12:15:13+00:00 manager-regression-restore--db-node-5bfd7570-1-3     !INFO | scylla[8258]:  [shard 0] repair - repair[9a499d32-2e20-48be-bd5e-3bae3a28393e]: completed successfully
```

**Comment by mykaul** [comment]
@ShlomiBalalis - any news on what's going on here?

**Comment by Michal-Leszczynski** [comment]
If I understand logs correctly, keyspace is being truncated 3 times in this test scenario:
```
< t:2023-05-02 11:26:49,747 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "TRUNCATE keyspace1.standard1" 10.142.0.247 9042"...
< t:2023-05-02 11:35:30,488 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "TRUNCATE keyspace1.standard1" 10.142.0.247 9042"...
< t:2023-05-02 11:42:46,529 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "TRUNCATE keyspace1.standard1" 10.142.0.247 9042"...
```
Since restored backup (`backup/8be4c092-8dcd-4766-9b43-ec7153e0e6ac` with `sm_20230502114137UTC`) started at 11:41:35:
```
May 02 11:41:35  {"L":"INFO","T":"2023-05-02T11:41:35.081Z","N":"scheduler","M":"PutTask","task":"backup/8be4c092-8dcd-4766-9b43-ec7153e0e6ac","schedule":{"cron":"","window":null,"timezone":"UTC","start_date":"0001-01-01T00:00:00Z","interval":"","num_retries":3,"retry_wait":"10m"},"properties":{"keyspace":["keyspace1"],"location":["gcs:manager-backup-tests-sct-project-1-us-east1"]},"create":true,"_trace_id":"8I_F8INdSUKl9EMikDbA5Q"}
```
We try to restore backup which contains already truncated keyspace, so we don't restore anything in this case. That's why the restore ended so fast and progress information does not include percentage (0/0).

You can also observe that by having a closer look at displayed progress information:
```
 ──────────────┬──────────┬──────────┬──────────┬──────────────┬────────╮
│ Host         │ Progress │     Size │  Success │ Deduplicated │ Failed │
├──────────────┼──────────┼──────────┼──────────┼──────────────┼────────┤
│ 10.138.0.50  │     100% │ 353.856k │ 353.856k │     353.856k │      0 │
│ 10.142.0.247 │     100% │ 351.474k │ 351.474k │     351.474k │      0 │
| 10.142.0.40  │     100% │ 353.585k │ 353.585k │     353.585k │      0 │
╰──────────────┴──────────┴──────────┴──────────┴──────────────┴────────╯
```
Where the size of the backup is really small, since it only contains data from keyspaces like `system_schema`, `system_auth`, etc. For comparison, this is the progress of the first backup (`ad2e1346-0915-4d99-bab2-317dbd152cf2`):
```
╭──────────────┬──────────┬──────────┬──────────┬──────────────┬────────╮
│ Host         │ Progress │     Size │  Success │ Deduplicated │ Failed │
├──────────────┼──────────┼──────────┼──────────┼──────────────┼────────┤
│ 10.138.0.50  │     100% │ 945.128M │ 945.128M │            0 │      0 │
│ 10.142.0.247 │     100% │ 944.958M │ 944.958M │            0 │      0 │
│ 10.142.0.40  │     100% │ 945.077M │ 945.077M │            0 │      0 │
╰──────────────┴──────────┴──────────┴──────────┴──────────────┴────────╯
```

**Comment by Michal-Leszczynski** [comment]
@ShlomiBalalis ping
