### ISSUE TITLE
test_client_encryption fails due to the repair task unable to fail fast when it meets server authentication

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-manager#3511]
Test code https://github.com/scylladb/scylla-cluster-tests/blob/6e3d34cd1b9fc6533a4e5a3874fd36ad401b9a81/mgmt_cli_test.py#L694-L729

Sanity test failure:
```
[2023-07-30T06:09:27.175Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 68, in wait_for
[2023-07-30T06:09:27.175Z] res = retry(func, **kwargs)
[2023-07-30T06:09:27.175Z] File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
[2023-07-30T06:09:27.175Z] do = self.iter(retry_state=retry_state)
[2023-07-30T06:09:27.175Z] File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
[2023-07-30T06:09:27.175Z] raise retry_exc.reraise()
[2023-07-30T06:09:27.175Z] File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 194, in reraise
[2023-07-30T06:09:27.175Z] raise self
[2023-07-30T06:09:27.175Z] tenacity.RetryError: RetryError[<Future at 0x7f597df0e260 state=finished returned bool>]
[2023-07-30T06:09:27.175Z] The above exception was the direct cause of the following exception:
[2023-07-30T06:09:27.175Z] Traceback (most recent call last):
[2023-07-30T06:09:27.175Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 399, in wait_for_status
[2023-07-30T06:09:27.175Z] return wait.wait_for(func=self.is_status_in_list, step=step, throw_exc=True,
[2023-07-30T06:09:27.175Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 79, in wait_for
[2023-07-30T06:09:27.175Z] raise WaitForTimeoutError(err) from ex
[2023-07-30T06:09:27.175Z] sdcm.wait.WaitForTimeoutError: Wait for: Waiting until task: repair/556d2527-0819-47ed-a2be-dfb4835c19ec reaches status of: ['ERROR', 'ERROR (4/4)']: timeout - 240 seconds - expired
[2023-07-30T06:09:27.175Z] The above exception was the direct cause of the following exception:
[2023-07-30T06:09:27.175Z] Traceback (most recent call last):
[2023-07-30T06:09:27.175Z] File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 381, in test_manager_sanity
[2023-07-30T06:09:27.175Z] self.test_client_encryption()
[2023-07-30T06:09:27.175Z] File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 724, in test_client_encryption
[2023-07-30T06:09:27.175Z] repair_task.wait_for_status(list_status=[TaskStatus.ERROR, TaskStatus.ERROR_FINAL], step=5, timeout=240)
[2023-07-30T06:09:27.175Z] File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 403, in wait_for_status
[2023-07-30T06:09:27.175Z] raise WaitForTimeoutError(
[2023-07-30T06:09:27.175Z] sdcm.wait.WaitForTimeoutError: Failed on waiting until task: repair/556d2527-0819-47ed-a2be-dfb4835c19ec reaches status of ['ERROR', 'ERROR (4/4)']: current task status RUNNING: Wait for: Waiting until task: repair/556d2527-0819-47ed-a2be-dfb4835c19ec reaches status of: ['ERROR', 'ERROR (4/4)']: timeout - 240 seconds - expired
```

**Comment by dkropachev** [comment]
To update `test_client_encryption` after it is done
