### ISSUE TITLE
TestBackupResumeIntegration can randomly fail

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-manager#3553]
```
panic: Fail in goroutine after TestBackupResumeIntegration/resume_after_stop has completed

goroutine 3543 [running]:
testing.(*common).Fail(0xc00089a340)
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:824 +0xe5
testing.(*common).Error(0xc00089a340, {0xc00071bfa8?, 0x594e200f43b0fe1d?, 0x1511f0c0219e05ba?})
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:934 +0x58
github.com/scylladb/scylla-manager/v3/pkg/service/backup_test.TestBackupResumeIntegration.func4.1()
	/home/runner/work/scylla-manager/scylla-manager/pkg/service/backup/service_backup_integration_test.go:1002 +0x2b3
created by github.com/scylladb/scylla-manager/v3/pkg/service/backup_test.TestBackupResumeIntegration.func4
	/home/runner/work/scylla-manager/scylla-manager/pkg/service/backup/service_backup_integration_test.go:997 +0x265
make: *** [Makefile:138: pkg-integration-test] Error 2
```

**Comment by Michal-Leszczynski** [comment]
This error is encountered when backup is run when there is a schema disagreement in the cluster.
The main test workflow fails fast at `h.waitTransfersStarted()`, but the backup started in a separate goroutine waits for schema agreement longer, runs and finishes the backup without any context error and that's why it fails. 
```
2023-09-01T15:14:41.8272639Z === RUN   TestBackupResumeIntegration/resume_after_stop
2023-09-01T15:14:41.9054432Z 15:14:41.905	[34mINFO[0m	client	Checking hosts connectivity	{"hosts": ["192.168.200.11", "192.168.200.12", "192.168.200.13"]}
2023-09-01T15:14:41.9071496Z 15:14:41.906	[34mINFO[0m	client	Host check OK	{"host": "192.168.200.11"}
2023-09-01T15:14:41.9076874Z 15:14:41.907	[34mINFO[0m	client	Host check OK	{"host": "192.168.200.12"}
2023-09-01T15:14:41.9093972Z 15:14:41.909	[34mINFO[0m	client	Host check OK	{"host": "192.168.200.13"}
2023-09-01T15:14:41.9098778Z 15:14:41.909	[34mINFO[0m	client	Done checking hosts connectivity
2023-09-01T15:14:41.9103345Z --- When: backup is running
2023-09-01T15:14:41.9109787Z 15:14:41.910	[34mINFO[0m	backup	Initializing backup	{"cluster_id": "7dce3530-2314-434c-b477-bb837ca73a8e", "task_id": "5c3b7292-c336-40f6-be0d-82c6dedc2eef", "run_id": "46853e53-48da-11ee-8952-6045bd81b57c", "target": {"units":[{"keyspace":"backuptest_resume","all_tables":false}],"dc":["dc1"],"location":["s3:backuptest-resume"],"retention":2,"retention_days":0,"rate_limit":["dc1:1"],"continue":true}}
2023-09-01T15:14:41.9746258Z 15:14:41.974	[34mINFO[0m	backup.await_schema	Awaiting schema agreement...
2023-09-01T15:14:41.9914536Z 15:14:41.990	[34mINFO[0m	backup.await_schema	Schema agreement not reached, retrying...	{"error": "cluster schema versions not consistent: [9b26e489-416b-386b-a96f-050b84fd5bf1 e22638b5-ead3-34d2-95a0-40d7d60df70b]", "wait": "12.578334356s"}
2023-09-01T15:14:46.9149689Z     service_backup_integration_test.go:227: timeout 5s
```
Increasing the timeout of `waitCond` should solve this issue.
