### ISSUE TITLE
Restore is failing with scylla master, upload directory not found

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-manager#3603]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

A test is trying to restore an old backup, and the test isn't finishing:
```
2023-10-07 09:41:29.430: (DisruptionEvent Severity.ERROR) period_type=end event_id=cddfe547-02b8-4311-b56c-463efb21cc4d duration=1m1s: nemesis_name=MgmtRestore target_node=Node longevity-50gb-12h-master-db-node-c41273bc-3 [3.250.88.181 | 10.4.8.138] (seed: True) errors=Schema restoration of sm_20230702185929UTC has failed!
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5045, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2793, in disrupt_mgmt_restore
assert restore_task.status == TaskStatus.DONE, f'Schema restoration of {chosen_snapshot_tag} has failed!'
AssertionError: Schema restoration of sm_20230702185929UTC has failed!
```

and then manager is trying to restore into non existing directory (data:system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/upload):
```
Oct 07 09:41:18 longevity-50gb-12h-master-monitor-node-c41273bc-1 scylla-manager[30981]: {"L":"INFO","T":"2023-10-07T09:41:18.722Z","N":"backup.restore","M":"Awaiting schema agreement...","_trace_id":"TMgxxMO2S4iudy71nr0mvA"}
Oct 07 09:41:18 longevity-50gb-12h-master-monitor-node-c41273bc-1 scylla-manager[30981]: {"L":"INFO","T":"2023-10-07T09:41:18.725Z","N":"backup.restore","M":"Done awaiting schema agreement","duration":"2.09628ms","_trace_id":"TMgxxMO2S4iudy71nr0mvA"}
Oct 07 09:41:18 longevity-50gb-12h-master-monitor-node-c41273bc-1 scylla-manager[30981]: {"L":"INFO","T":"2023-10-07T09:41:18.725Z","N":"backup.restore","M":"Started restoring schema","_trace_id":"TMgxxMO2S4iudy71nr0mvA"}
Oct 07 09:41:18 longevity-50gb-12h-master-monitor-node-c41273bc-1 scylla-manager[30981]: {"L":"INFO","T":"2023-10-07T09:41:18.735Z","N":"backup.restore","M":"Received table's version","keyspace":"system_schema","table":"columns","version":"24101c25a2ae3af787c1b40ee1aca33f","_trace_id":"TMgxxMO2S4iudy71nr0mvA"}
Oct 07 09:41:18 longevity-50gb-12h-master-monitor-node-c41273bc-1 scylla-manager[30981]: {"L":"INFO","T":"2023-10-07T09:41:18.738Z","N":"backup.restore","M":"Restoring schema finished","_trace_id":"TMgxxMO2S4iudy71nr0mvA"}
Oct 07 09:41:18 longevity-50gb-12h-master-monitor-node-c41273bc-1 scylla-manager[30981]: {"L":"INFO","T":"2023-10-07T09:41:18.746Z","N":"scheduler.0d2d2531","M":"Run ended with ERROR","task":"restore/60cd3438-07cc-48c1-8054-73e6ea075d5a","status":"ERROR","cause":"restore data: list dir: data:system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/upload on host: 10.4.11.166: agent [HTTP 404] error in ListJSON: directory not found","duration":"3.797200994s","_trace_id":"TMgxxMO2S4iudy71nr0mvA"}
```
## Impact

A user can't restore an old backup

## How frequently does it reproduce?

it's seen multiple times in that one run

## Installation details

Kernel Version: 5.15.0-1047-aws
Scylla version (or git commit hash): `5.4.0~dev-20231006.498e3ec435be` with build-id `16c6112202348a8adba536b4195d48adfdf958f9`

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-c41273bc-6 (3.253.75.192 | 10.4.9.179) (shards: 14)
- longevity-50gb-12h-master-db-node-c41273bc-5 (34.244.114.28 | 10.4.8.235) (shards: 10)
- longevity-50gb-12h-master-db-node-c41273bc-4 (52.208.191.49 | 10.4.11.22) (shards: 12)
- longevity-50gb-12h-master-db-node-c41273bc-3 (3.250.88.181 | 10.4.8.138) (shards: 10)
- longevity-50gb-12h-master-db-node-c41273bc-2 (3.250.6.28 | 10.4.8.193) (shards: 9)
- longevity-50gb-12h-master-db-node-c41273bc-1 (54.171.231.36 | 10.4.11.166) (shards: 9)

OS / Image: `ami-06f33c2dc88569dd3` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `c41273bc-9c9b-45cb-aaae-1b92045436b0`
Test name: `scylla-master/longevity/longevity-150gb-asymmetric-cluster-12h-test`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0ebb9363e3e989e2ef5097caaabb112319307511/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c41273bc-9c9b-45cb-aaae-1b92045436b0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c41273bc-9c9b-45cb-aaae-1b92045436b0)
- Show all stored logs command: `$ hydra investigate show-logs c41273bc-9c9b-45cb-aaae-1b92045436b0`

## Logs:
- **db-cluster-c41273bc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/db-cluster-c41273bc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/db-cluster-c41273bc.tar.gz)
- **sct-runner-events-c41273bc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/sct-runner-events-c41273bc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/sct-runner-events-c41273bc.tar.gz)
- **sct-c41273bc.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/sct-c41273bc.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/sct-c41273bc.log.tar.gz)
- **loader-set-c41273bc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/loader-set-c41273bc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/loader-set-c41273bc.tar.gz)
- **monitor-set-c41273bc.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/monitor-set-c41273bc.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c41273bc-9c9b-45cb-aaae-1b92045436b0/20231008_041531/monitor-set-c41273bc.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-150gb-asymmetric-cluster-12h-test/23/)
[Argus](https://argus.scylladb.com/test/6a3a708c-caa0-439f-84cd-736b40b517e3/runs?additionalRuns[]=c41273bc-9c9b-45cb-aaae-1b92045436b0)
</details>

**Comment by fruch** [comment]
seem like this is error is coming from:
https://github.com/scylladb/scylla-manager/blob/7929417cc5283cf874e710db7b86db909ea7751a/pkg/service/backup/restore_worker.go#L228

while I can see in the node logs that `/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f` exists and we have files there.

the only thing I can't see if upload directory exists

**Comment by fruch** [comment]
recent change in scylla was touching the way those directories are created: https://github.com/scylladb/scylladb/pull/15480

**Comment by Michal-Leszczynski** [comment]
The restore schema process starts by listing and cleaning upload dir, so it assumes that `/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/upload` should exist. This error is returned when trying to list this dir.

**Comment by Michal-Leszczynski** [comment]
@fruch Is it possible to run this test with a Scylla that does not contain mentioned https://github.com/scylladb/scylladb/pull/15480? I thought that it is safe to assume that upload dir exists?

**Comment by fruch** [comment]
nope, `5.4.0~dev-20231006.498e3ec435b` does have commits from: https://github.com/scylladb/scylladb/pull/15480

**Comment by Michal-Leszczynski** [comment]
@bhalevy could you take a look at this?
It seems like in this test the `system_schema.columns` upload dir is missing and it makes restore fail.

**Comment by bhalevy** [comment]
Who creates `system_schema.columns`?  Scylla, or maybe the restore logic creates for restoring the schema prior to restoring the user tables?

**Comment by Michal-Leszczynski** [comment]
> Who creates system_schema.columns? Scylla, or maybe the restore logic creates for restoring the schema prior to restoring the user tables?

Here SM is trying to restore backed-up cluster schema without touching user data. SM restores schema by putting schema sstables in corresponding upload dir, but it assumes that all directories are already there. Even though `/var/lib/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f` exists, it seems like SM does not see its upload dir.

**Comment by bhalevy** [comment]
@xemul can you please check if scylla creates the upload directory for system tables?

**Comment by xemul** [comment]
Great catch, @bhalevy :) It _did_ that before scylladb/scylladb@9c3e055d22b2aaeadc9108c9a2d8f1ae90f44059 . After it it touches main dir, staging one and checks if quarantine exists. The upload dir is missing

**Comment by xemul** [comment]
https://github.com/scylladb/scylladb/issues/15708
