### ISSUE TITLE
Execute scylla-manager BACKUP & RESTORE integration tests against tablets enabled environment

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3703]
To validate what additional work may be needed on the Scylla Manager side to provide full support for BACKUP & RESTORE procedures with Scylla having tablet support enabled, we need to create the possibility of establishing a tablet-enabled environment in the docker-compose environment we use for testing.

Here is a brief description of what happens during the backup process (https://github.com/scylladb/scylla-manager/blob/master/pkg/service/backup/README.md): Scylla Manager (SM) calls POST /storage_service/snapshot to prepare SSTables that are going to be backed up. An open question is whether the endpoint can be called at any given moment in a tablet-enabled environment or if there are any prerequisites for this action (cc: @bhalevy).

Here is a brief description of what happens during the restore process (https://github.com/scylladb/scylla-manager/blob/master/pkg/service/restore/README.md): POST /storage_service/sstables/{keyspace} is called with the load&stream flag enabled after copying files to the expected destination.

Backup suites will test if backup is possible in a tablet-enabled environment. Restore suites will answer whether we can back up the data in a tablet-enabled environment and bring it back to the new, tablet-enabled cluster.

This is just a supplement to the SCT tests that are supposed to check the backup and restore with tablets too.

Reference to scylla.yaml https://github.com/scylladb/scylladb/blob/0cbf8f75f0163898cd6359b843f8c9d3237177f3/conf/scylla.yaml#L277-L284 (cc: @Michal-Leszczynski )

**Comment by bhalevy** [comment]
Cc @ShlomiBalalis

**Comment by Michal-Leszczynski** [comment]
One small thing that will need to be changed in backup, is that backup uses `DescribeRing` to skip some keyspaces.

**Comment by bhalevy** [comment]
Ref https://github.com/scylladb/scylladb/issues/16846

**Comment by yarongilor** [comment]
@bhalevy , @ShlomiBalalis , can you please advise, what about support of manager-repair cmd?
it currently failed with:
```
2024-05-16 11:32:13.099: (DisruptionEvent Severity.ERROR) period_type=end event_id=bad809cf-ddab-4454-87df-a5f70a4a5c72 duration=2m3s: nemesis_name=MgmtCorruptThenRepair target_node=Node longevity-100gb-4h-master-db-node-d6d9cb1d-8 [18.201.71.67 | 10.4.8.4] errors=Encountered an error on sctool command: repair -c af623ecc-a5c1-4922-be7a-7fe40de22ef5: Encountered a bad command exit code!
Command: 'sudo sctool repair -c af623ecc-a5c1-4922-be7a-7fe40de22ef5'
Exit code: 1
Stdout:
Stderr:
Error: create repair target: create repair plan: keyspace keyspace1: get ring description: giving up after 6 attempts: agent [HTTP 500] std::runtime_error (The keyspace keyspace1 has tablet table. Query describe_ring with the table parameter!)
Trace ID: vQBvluZzSAWn4uuc5sEvgQ (grep in scylla-manager logs)
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1129, in run
res = self.manager_node.remoter.sudo(f"sctool {cmd}")
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo
return self.run(cmd=cmd,
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo sctool repair -c af623ecc-a5c1-4922-be7a-7fe40de22ef5'
Exit code: 1
Stdout:
Stderr:
Error: create repair target: create repair plan: keyspace keyspace1: get ring description: giving up after 6 attempts: agent [HTTP 500] std::runtime_error (The keyspace keyspace1 has tablet table. Query describe_ring with the table parameter!)
Trace ID: vQBvluZzSAWn4uuc5sEvgQ (grep in scylla-manager logs)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5117, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2989, in disrupt_mgmt_corrupt_then_repair
self._mgmt_repair_cli()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 178, in wrapped
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2994, in _mgmt_repair_cli
mgr_task = mgr_cluster.create_repair_task()
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 634, in create_repair_task
res = self.sctool.run(cmd=cmd, parse_table_res=False)
File "/home/ubuntu/scylla-cluster-tests/sdcm/mgmt/cli.py", line 1132, in run
raise ScyllaManagerError(f"Encountered an error on sctool command: {cmd}: {ex}") from ex
sdcm.mgmt.common.ScyllaManagerError: Encountered an error on sctool command: repair -c af623ecc-a5c1-4922-be7a-7fe40de22ef5: Encountered a bad command exit code!
Command: 'sudo sctool repair -c af623ecc-a5c1-4922-be7a-7fe40de22ef5'
Exit code: 1
Stdout:
Stderr:
Error: create repair target: create repair plan: keyspace keyspace1: get ring description: giving up after 6 attempts: agent [HTTP 500] std::runtime_error (The keyspace keyspace1 has tablet table. Query describe_ring with the table parameter!)
Trace ID: vQBvluZzSAWn4uuc5sEvgQ (grep in scylla-manager logs)
```
https://argus.scylladb.com/test/bfb2ef96-b741-43ea-9e7d-82e652c0ebdc/runs?additionalRuns[]=d6d9cb1d-7343-4283-b3b6-9e7e9dcf0cc3

**Comment by Michal-Leszczynski** [comment]
@yarongilor I see that those tests run against SM 3.2.7, but tablet repair support is only on SM master.
