### ISSUE TITLE
[SCT] Test adjustments for Manager 3.3 and Scylla 6.0

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#3904]
We faced a couple of test issues during Manager release 3.3 testing with Scylla 6.0.

Here is a list of fixes that should be implemented for SCT tests to address these issues:

1. Fix expected result of `test_enospc_before_restore` to wait for DONE task status instead of ERROR if the Scylla is 6.0 and higher.
CI: https://jenkins.scylladb.com/view/scylla-manager/job/manager-3.3/view/Backup/job/sct-feature-test-backup/5
```
18:17:09  2024-06-24 16:16:14.870: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=e325066b-117e-4864-9cc0-b2eff4979c6b, source=MgmtCliTest.test_backup_feature (mgmt_cli_test.MgmtCliTest) [Test Restore end of space]() message=Traceback (most recent call last):
18:17:09  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 506, in test_backup_feature
18:17:09  self.test_enospc_before_restore()
18:17:09  File "/home/ubuntu/scylla-cluster-tests/mgmt_cli_test.py", line 911, in test_enospc_before_restore
18:17:09  assert final_status == TaskStatus.ERROR, \
18:17:09  AssertionError: The restore task is supposed to fail, since node Node manager-regression-manager--db-node-077f529d-2 [44.223.108.238 | 10.12.0.233] (dc name: us-eastscylla_node_east) lacks the disk space to downloadthe snapshot files
```

2. Update the initial Manager version in Upgrade tests from 3.1 to 3.2.

**Comment by mikliapko** [comment]
> 1. Fix expected result of `test_enospc_before_restore` to wait for DONE task status instead of ERROR if the Scylla is 6.0 and higher.

Blocked by issue https://github.com/scylladb/scylla-manager/issues/3907. Will be tracked there. So, no need to keep this task open.

> 2. Update the initial Manager version in Upgrade tests from 3.1 to 3.2.

Addressed here https://github.com/scylladb/scylla-cluster-tests/pull/7767
